name: CI and Docker Image Update

# Act when push and pull_request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Actions
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.10"

    # - name: Cache pip packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Makefile commands
      run: |
        make format 
        make lint
        continue-on-error: true
        
    - name: Run app.py to check for errors
      run: |
          python ./app.py

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: dandanrao/19f_nmr_predictor:latest

          
   
